CREATE TABLE IF NOT EXISTS `estudo`.`ESTADOS` (
  `id_estados` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `sigla` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Estados`))
ENGINE = InnoDB